version: "1.0.0"
services:
  post-postgres-db:
    image: postgres
    container_name: post-postgres-db
    env_file:
      - .env
    ports:
      - '5433:5432'
    networks:
      - post-net
    restart: always
  post-service:
    image: post-service:1.0.0
    container_name: post-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8081:8081'
      - '5005:5005'
    networks:
      - post-net
    depends_on:
      - post-postgres-db
networks:
  post-net:
    name: post-net
    attachable: true
    driver: bridge