version: "1.0.0"
services:
  ginfo-postgres-db:
    image: postgres
    container_name: ginfo-postgres-db
    env_file:
      - .env
    ports:
      - '5433:5432'
    networks:
      - ginfo-net
    restart: always
  ginfo-service:
    image: ginfo-service:1.0.0
    container_name: ginfo-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8081:8081'
      - '5005:5005'
    networks:
      - ginfo-net
    depends_on:
      - ginfo-postgres-db
networks:
  ginfo-net:
    name: ginfo-net
    attachable: true
    driver: bridge